### ISSUE TITLE
Calibre import error: __init__.py missing from top level folder

### ISSUE THREAD

**Issue by riverLethe9** [bkanuka/calibre-plugin-hide-statusbar#1]
When attempting to load the plugin, Calibre throws this error. Here are the details:

> calibre, version 5.25.0
> ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Users/stuartlombard/Downloads/calibre-plugin-hide-statusbar-master.zip' is invalid. It does not contain a top-level __init__.py file
> calibre 5.25  embedded-python: True is64bit: True
> macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64')
> Python 3.8.5
> OSX: ('10.16', ('', '', ''), 'x86_64')
> Interface language: None
> Successfully initialized third party plugins: DeDRM (7, 2, 1) && Hide Statusbar (1, 0, 0)
> Traceback (most recent call last):
>   File "calibre/gui2/preferences/plugins.py", line 327, in add_plugin
>   File "calibre/customize/ui.py", line 477, in add_plugin
>   File "calibre/customize/ui.py", line 65, in load_plugin
>   File "calibre/customize/zipplugin.py", line 284, in load
>   File "calibre/customize/zipplugin.py", line 379, in _locate_code
> calibre.customize.InvalidPlugin: The plugin in '/Users/stuartlombard/Downloads/calibre-plugin-hide-statusbar-master.zip' is invalid. It does not contain a top-level __init__.py file

Nonetheless, when I restarted Calibre, the plugin appears to have been successfully loaded. So I am not sure whether the issue is with the plugin or with Calibre, given that your plugin clearly has the __init__.py file in the top level.

![Screenshot 2021-08-20 at 11 23 45](https://user-images.githubusercontent.com/29024715/130264431-27a5b6af-8b84-492f-9a00-d9e09750f0f8.png)

**Comment by nessust** [comment]
CALIBRE 5.44 
Extract the zip file. Look for those files .py and then compress them. Use the zip created as plugin.
![Captura de pantalla 2022-09-08 a las 13 09 00](https://user-images.githubusercontent.com/63145802/189107519-60371674-b67b-4d0e-bf59-3b070ac8f722.png)

First line on ui.py is #!/usr/bin/env python2          work in 10.14 set python path to version 3.9
but does not work keyboard shortcut `Ctrl+Shift+S`

I'll try now with py 3.9
